### ISSUE TITLE
install hangs: rustup run nightly-2016-08-01 cargo install --git https://github.com/murarth/rusti

### ISSUE THREAD

**Issue by izelnakri** [murarth/rusti#101]
the target rust is more than 2 years old and installing with it hangs on: Updating registry `https://github.com/rust-lang/crates.io-index`. Can we get an update with a more up-to-date rust?

**Comment by murarth** [comment]
No, it's not possible to build rusti with any later version of Rust. (See #86)

You say that it hangs while updating the crates.io registry. How long did you allow it to run before interrupting it? Older versions of cargo did not display a progress bar when executing this operation. Is it possible that it simply wasn't allowed enough time to complete?
