### ISSUE TITLE
Segmentation fault when calling `llvm::LLVMGetPointerToGlobal` on Windows (LLVM ERROR: Incompatible object format!)

### ISSUE THREAD

**Issue by bombless** [murarth/rusti#15]
I tried cleaning $PATH, using different rustc (dev or nightly), no good so far, always the same segmentation fault no matter you run from cli or repl.

```
bombless@bombless-PC ~/rusti
$ target/rusti.exe -e 0
DEBUG - searching for sysroot in PATH D:\msys64rust\mingw32\bin;D:\msys64rust\usr\local\bin;D:\msys64rust\usr\bin;D:\msys64rust\usr\bin;D:\msys64rust\home\bombless\rust\i686-pc-windows-gnu\stage1\bin
DEBUG - sysroot from PATH entry D:\msys64rust\home\bombless\rust\i686-pc-windows-gnu\stage1\bin
DEBUG - loading crate D:\msys64rust\home\bombless\rust\i686-pc-windows-gnu\stage1\bin\rustlib\i686-pc-windows-gnu\lib\std-4e7c5e5c.dll
DEBUG - compiling module
DEBUG - loading crate D:\msys64rust\home\bombless\rust\i686-pc-windows-gnu\stage1\bin\rustlib\i686-pc-windows-gnu\lib\std-4e7c5e5c.dll
LLVM ERROR: Incompatible object format!
Segmentation fault


bombless@bombless-PC ~/rusti
$ rustc -V -v
rustc 1.0.0-dev (b6d91a2bd 2015-02-15 07:53:07 +0000)
binary: rustc
commit-hash: b6d91a2bdac45cd919497a24207fab843124d4ba
commit-date: 2015-02-15 07:53:07 +0000
host: i686-pc-windows-gnu
release: 1.0.0-dev

bombless@bombless-PC ~/rusti
$
```

**Comment by murarth** [comment]
Apparently, LLVM MCJIT doesn't understand Windows executable formats, even on Windows. This [mailing list posting](http://lists.cs.uiuc.edu/pipermail/llvmdev/2013-December/068395.html) indicates that adding `-elf` to the end of the target triple will cause LLVM to generate ELF code in memory on Windows. The Rust LLVM JIT code should be doing this, but I'm not sure how to do it. I will be looking into it.

**Comment by murarth** [comment]
@bombless: I've written a very naive attempt to fix this. I have no idea whether it will work at all. It's in a branch in this repo called `windows-fix`. If you'd try it and let me know if it succeeds or if the output changes, I'd appreciate it.

**Comment by bombless** [comment]
@murarth Thanks!
I tried your idea but it seems that changing the triple here don't work.

```
$ target/rusti.exe -e 0
error: Error loading target specification: Could not find specification for target "i686-pc-windows-gnu-elf"
thread '<main>' panicked at 'ExecutionEngine init input failed to compile', C:\bot\slave\nightly-dist-rustc-win-32\build\src\libcore\option.rs:330
```

```
$ target/rusti -e 0
DEBUG - searching for sysroot in PATH D:\msys64rust\mingw32\bin;D:\msys64rust\usr\local\bin;D:\msys64rust\usr\bin;D:\msys64rust\usr\bin;D:\rust\bin;C:\program files (x86)\cmake\bin;D:\msys64rust\usr\bin\site_perl;D:\msys64rust\usr\bin\vendor_perl;D:\msys64rust\usr\bin\core_perl
DEBUG - sysroot from PATH entry D:\rust\bin
error: Error loading target specification: Could not find specification for target "i686-pc-mingw32-elf"
thread '<main>' panicked at 'ExecutionEngine init input failed to compile', C:\bot\slave\nightly-dist-rustc-win-32\build\src\libcore\option.rs:330
```

```
$ target/rusti.exe -e 0
DEBUG - searching for sysroot in PATH D:\msys64rust\mingw32\bin;D:\msys64rust\usr\local\bin;D:\msys64rust\usr\bin;D:\msys64rust\usr\bin;D:\rust\bin;C:\program files (x86)\cmake\bin;D:\msys64rust\usr\bin\site_perl;D:\msys64rust\usr\bin\vendor_perl;D:\msys64rust\usr\bin\core_perl
DEBUG - sysroot from PATH entry D:\rust\bin
error: Error loading target specification: Could not find specification for target "i686-pc-windows-elf"
thread '<main>' panicked at 'ExecutionEngine init input failed to compile', C:\bot\slave\nightly-dist-rustc-win-32\build\src\libcore\option.rs:330
```


I tried to edit that `sys::getProcessTriple()` and recompile rustc to get new rustc library but it doesn't work, with same output.

**Comment by bombless** [comment]
Changing source code of src/llvm only affects libraries built on stage1 (I read Makefile before but I forgot this thing yesterday).
Leaving this message so if anyone view this issue and try the same thing as me can save some time.

**Comment by murarth** [comment]
@bombless: I think this issue has been solved by a recent rust-lang change that landed in nightly `(2228ce10c 2015-06-09)`. Can you confirm?

**Comment by bombless** [comment]
I compiled rusti with latest rustc but it seems that recent change of libsyntax breaks the code.
I'll look into it later.

**Comment by murarth** [comment]
@bombless: Yes, there was a breaking change today. `(fbb13543f 2015-06-11)` is the latest nightly and rusti should compile with that nightly build.

**Comment by bombless** [comment]
Cheers, it works!
