### ISSUE TITLE
LLVM ERROR: Program used external function '___morestack_addr' which could not be resolved!

### ISSUE THREAD

**Issue by yann-ledu** [murarth/rusti#17]
This is what I get whatever I type.

**Comment by murarth** [comment]
This appears to be a duplicate of #14 (which shouldn't have been closed). Are you also using OS X?

**Comment by yann-ledu** [comment]
Yes

**Comment by murarth** [comment]
Okay, closing this in favor of the aforementioned issue, which I've reopened.
