### ISSUE TITLE
src/rusti/input.rs:31:38: 31:45 error: unresolved import `syntax::parse::PResult`. There is no `PResult` in `syntax::parse`

### ISSUE THREAD

**Issue by sheganinans** [murarth/rusti#24]
$ cargo build --verbose
       Fresh regex v0.1.26
       Fresh libc v0.1.5
       Fresh log v0.3.1
   Compiling rusti v0.0.1 (file:///home/aistis/Projects/rusti)
     Running `rustc src/rusti/lib.rs --crate-name rusti --crate-type lib -g -C metadata=0f5b8a2f76fd202b -C extra-filename=-0f5b8a2f76fd202b --out-dir /home/aistis/Projects/rusti/target/debug --emit=dep-info,link -L dependency=/home/aistis/Projects/rusti/target/debug -L dependency=/home/aistis/Projects/rusti/target/debug/deps --extern log=/home/aistis/Projects/rusti/target/debug/deps/liblog-54cf393d3c69686f.rlib --extern getopts=/home/aistis/Projects/rusti/target/debug/deps/libgetopts-13bfb58dc9e184de.rlib --extern env_logger=/home/aistis/Projects/rusti/target/debug/deps/libenv_logger-0e0d1edb8b8745e2.rlib`
       Fresh getopts v0.2.9
       Fresh env_logger v0.3.0
src/rusti/input.rs:31:38: 31:45 error: unresolved import `syntax::parse::PResult`. There is no `PResult` in `syntax::parse`
src/rusti/input.rs:31 use syntax::parse::{classify, token, PResult};
                                                           ^~~~~~~
error: aborting due to previous error
Could not compile `rusti`.

Caused by:
  Process didn't exit successfully: `rustc src/rusti/lib.rs --crate-name rusti --crate-type lib -g -C metadata=0f5b8a2f76fd202b -C extra-filename=-0f5b8a2f76fd202b --out-dir /home/aistis/Projects/rusti/target/debug --emit=dep-info,link -L dependency=/home/aistis/Projects/rusti/target/debug -L dependency=/home/aistis/Projects/rusti/target/debug/deps --extern log=/home/aistis/Projects/rusti/target/debug/deps/liblog-54cf393d3c69686f.rlib --extern getopts=/home/aistis/Projects/rusti/target/debug/deps/libgetopts-13bfb58dc9e184de.rlib --extern env_logger=/home/aistis/Projects/rusti/target/debug/deps/libenv_logger-0e0d1edb8b8745e2.rlib` (exit code: 101)

**Comment by murarth** [comment]
You must be running an outdated Rust nightly build. Update to the latest nightly build (*not* the beta channel).

**Comment by sheganinans** [comment]
Hmm, I thought it might have been something like that.
