### ISSUE TITLE
latest rusti fails to build due to unstable feature with latest rust

### ISSUE THREAD

**Issue by GregDavidson** [murarth/rusti#26]
I was unable to build rusti with my previous beta.2 of rust so I installed the
latest beta.4 of rust and cloned the latest rusti.  I got the same problem:

$ cargo build
   Compiling libc v0.1.6
   Compiling regex v0.1.30
   Compiling log v0.3.1
   Compiling getopts v0.2.10
   Compiling env_logger v0.3.0
   Compiling rusti v0.0.1 (file:///home/greg/Play/Lang/Special/Rust/rusti)
src/rusti/lib.rs:12:1: 13:31 error: unstable feature
src/rusti/lib.rs:12 #![feature(collections, exit_status, libc, path_ext,
src/rusti/lib.rs:13     rustc_private, set_stdio)]
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `rusti`.

To learn more, run the command again with --verbose.

$ rustc --version
rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)

**Comment by murarth** [comment]
rusti relies on internal `rustc` APIs. There's no way to operate without them. For this reason, rusti simply cannot be built on beta. If you want to use rusti, you'll need to install Rust on the nightly channel. If you use [rustup](https://github.com/rust-lang/rustup), this can be done by passing `--channel=nightly` to the install script.
