### ISSUE TITLE
`.type` incorrectly classifies unboxed closures as a boxed closure

### ISSUE THREAD

**Issue by japaric** [murarth/rusti#3]
``` rust
// OK
rusti=> .t || 0i
|| 0i = || -> int
// Err
rusti=> .t |:| 0i
|:| 0i = 'static |()|:'static -> int
// Err
rusti=> .t |&:| 0i
|&:| 0i = 'static |()|:'static -> int
```

Unboxed closures have anonymous types, so maybe you could report them by their `Fn*` trait, like:

``` rust
|:| 0i = F where F: FnOnce() -> int
// or
|:| 0i = FnOnce() -> int implementor
```

(Or you could do what `rustc` does and just report them as `closure` :P)

**Comment by murarth** [comment]
As expected, `rustc` got around to changing its `Repr` output for closure types.

```rust
rusti=> .t || ()
|| () = [closure(())]
rusti=> .t || 1
|| 1 = [closure(()) -> i32]
rusti=> .t |i:i32| i
|i:i32| i = [closure((i32,)) -> i32]
```

**Comment by murarth** [comment]
If there's no objection, I'm going to close this now. The output is clearer than it was before and boxed closures don't even exist anymore (except for the `Box<Fn()>` variety).
