### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by Sarjo2222** [murarth/rusti#32]
Trying to build rusti gives this error:
	  
        Compiling rusti v0.0.1 (file:///Users/.../Documents/RProjects/rusti)
	error: linking with `cc` failed: exit code: 1
	note: "cc" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/.../Documents/RProjects/rusti/target/debug/rusti" "/Users/.../Documents/RProjects/rusti/target/debug/rusti.o" "-Wl,-force_load,/usr/local/lib/rustlib/x86_64-apple-darwin/lib/libmorestack.a" "-Wl,-dead_strip" "-nodefaultlibs" "/Users/.../Documents/RProjects/rusti/target/debug/librusti.rlib" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_driver-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_privacy-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_resolve-11582ce5" "/Users/.../Documents/RProjects/rusti/target/debug/deps/libenv_logger-63352e48193fbb80.rlib" "/Users/.../Documents/RProjects/rusti/target/debug/deps/liblog-54cf393d3c69686f.rlib" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_borrowck-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_trans-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_typeck-11582ce5" "/Users/.../Documents/RProjects/rusti/target/debug/deps/libregex-3bea3061fd389532.rlib" "/Users/.../Documents/RProjects/rusti/target/debug/deps/libgetopts-d6ecf60df5ea72e6.rlib" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_lint-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_back-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lsyntax-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lterm-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lgraphviz-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrbml-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-larena-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lflate-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_llvm-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lrustc_data_structures-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lserialize-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-llog-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lfmt_macros-11582ce5" "/Users/.../Documents/RProjects/rusti/target/debug/deps/libtempfile-1e8a000811fae654.rlib" "/Users/.../Documents/RProjects/rusti/target/debug/deps/librand-b924d9fc5b3eb5b8.rlib" "/Users/.../Documents/RProjects/rusti/target/debug/deps/liblibc-2eda841eb12a3090.rlib" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lgetopts-11582ce5" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-lstd-11582ce5" "-L" "/Users/.../Documents/RProjects/rusti/target/debug" "-L" "/Users/.../Documents/RProjects/rusti/target/debug/deps" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-L" "/Users/.../Documents/RProjects/rusti/.rust/lib/x86_64-apple-darwin" "-L" "/Users/.../Documents/RProjects/rusti/lib/x86_64-apple-darwin" "-lmorestack" "-lreadline" "-lpthread" "-ledit" "-lm" "-lc++" "-lc" "-lm" "-lSystem" "-lpthread" "-lc" "-lm" "-lcompiler-rt"
	note: ld: warning: directory not found for option '-L/Users/.../Documents/RProjects/rusti/.rust/lib/x86_64-apple-darwin'
	ld: warning: directory not found for option '-L/Users/.../Documents/RProjects/rusti/lib/x86_64-apple-darwin'
	Undefined symbols for architecture x86_64:
	  "_rl_completion_suppress_append", referenced from:
	      readline::completion_fn::__rust_abi in librusti.rlib(rusti.o)
	ld: symbol(s) not found for architecture x86_64
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

	error: aborting due to previous error
    Could not compile `rusti`.

Occurs on OS X 10.10.3 using rustc 1.2.0-nightly (0cc99f9cc 2015-05-17) (built 2015-05-17)

**Comment by murarth** [comment]
Can you tell me which version of Readline you have installed?

**Comment by Sarjo2222** [comment]
readline-6.3.8 (installed+linked with homebrew)

**Comment by murarth** [comment]
Hm. Apparently, that variable just doesn't exist in readline for some platforms. I'll have a fix for this soon.

**Comment by murarth** [comment]
I removed the variable, but then I realized that there's another variable that serves a similar purpose. Can you grep your readline include files and tell me whether `rl_completion_append_character` exists?

**Comment by Sarjo2222** [comment]
bash-3.2$ grep -r "rl_completion_append_character" /usr/local/Cellar/readline/*
/usr/local/Cellar/readline/6.3.8/CHANGES:    rl_completion_append_character to completed words.
/usr/local/Cellar/readline/6.3.8/include/readline/readline.h:extern int rl_completion_append_character;
/usr/local/Cellar/readline/6.3.8/include/readline/readline.h:   rl_completion_append_character will not be appended. */
Binary file /usr/local/Cellar/readline/6.3.8/lib/libreadline.6.2.dylib matches
Binary file /usr/local/Cellar/readline/6.3.8/lib/libreadline.6.3.dylib matches
Binary file /usr/local/Cellar/readline/6.3.8/lib/libreadline.6.dylib matches
Binary file /usr/local/Cellar/readline/6.3.8/lib/libreadline.a matches
Binary file /usr/local/Cellar/readline/6.3.8/lib/libreadline.dylib matches
/usr/local/Cellar/readline/6.3.8/share/doc/readline/CHANGES:    rl_completion_append_character to completed words.
/usr/local/Cellar/readline/6.3.8/share/info/readline.info: -- Variable: int rl_completion_append_character
/usr/local/Cellar/readline/6.3.8/share/info/readline.info:* rl_completion_append_character:        Completion Variables.

**Comment by murarth** [comment]
All right. Great. I've solved the issue and restored the original behavior.

**Comment by Sarjo2222** [comment]
This seems to have solved the problem. Thanks.
