### ISSUE TITLE
multiline input causes 'parse_program' thread to panic.

### ISSUE THREAD

**Issue by cjwelborn** [murarth/rusti#36]
Typing in a multiline statement (like a function definition) prints an error after every line, but seems to work otherwise.

I was just trying to type in some little function to make sure everything was working:
```rust
fn subber(i: i32) -> i32 {
    i - 1
}
```

Example:
```
rusti=> fn subber(i: i32) -> i32 {
thread 'parse_program' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/parse/mod.rs:244
rusti.> i - 1
thread 'parse_program' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/parse/mod.rs:244
rusti.> }
rusti=> println!("{}", subber(5));
4
rusti=>
```

I'm using the latest nightly from `multirust`:

- `rustc 1.2.0-nightly (613e57b44 2015-06-01) (built 2015-06-02)`
- `cargo 0.3.0-nightly (06dbe65 2015-05-29) (built 2015-06-01)`

**Comment by murarth** [comment]
The panic is normal, actually. The problem is that the panic message is being printed. I'll look into this. It shouldn't be a difficult fix.

**Comment by murarth** [comment]
Fixed. The problem was that the `env_logger` package recently set the default logging level to `Error`, which caused rusti to emit those messages.

**Comment by cjwelborn** [comment]
Awesome, thanks for the quick turnaround.
