### ISSUE TITLE
Implement a readline alternative on Windows

### ISSUE THREAD

**Issue by murarth** [murarth/rusti#39]
The recommended method of using GNU Readline on Windows is to install Cygwin, which is an unappealing option for some users.
A Windows version of the `rusti::readline` module could be implemented using Windows' console API.

**Comment by murarth** [comment]
cc @retep998

**Comment by bombless** [comment]
Hmm I just copy 2 dll files of readline to rustlib directory to compile rusti on Windows.
What is that cygwin thing?

**Comment by murarth** [comment]
Oh. Well, I suppose it would still be nice to remove the unnecessary dependency. Most Unix systems have readline installed, but it's an extra step for most Windows users.

**Comment by bombless** [comment]
Hmm maybe we first remove the feature to scroll up line history for Windows, then the fix will be easier.
I cannot scroll up because the up arrow key function differently in MSYS/CYGWIN shell.
(I believe this is a bug long time ago but it seems that nobody cares.)

**Comment by bombless** [comment]
(like this easy https://github.com/bombless/rusti/commit/980c575b62dc597f9cd67400e999fe1765418d8c )

**Comment by bombless** [comment]
nvm I'll try make another crate to wrap readline and then do something like [this](https://github.com/conradkleinespel/rustastic-password/blob/b07a349becbed49a84c0ce4db607d4b918ad8a2e/Cargo.toml) (which looks awful)

**Comment by murarth** [comment]
@bombless: I don't intend to remove any features for either Windows or Unix platforms. The goal is to continue using readline on Unix systems, but use an alternative on Windows that provides basic functionality. The idea being that Unix users will generally expect a readline-like interface, as is used by popular shell and REPL utilities.

I don't know what sort of interface popular Windows shells and REPLs have, but if the Windows alternative has line editing (which I'm to understand is part of Windows' console API) and history support, that would be a good start.

I don't think any crazy trickery with dependencies should be necessary. The Unix dependency on readline is inferred by the `extern "C"` definition in `readline.rs`. Equivalent Windows functionality may need a Windows-specific dependency, but that shouldn't be much trouble.

**Comment by ritalin** [comment]
@murarth I've found [readline module](https://github.com/shaleh/rust-readline) implemented in pure rust.
Can you apply this module?

**Comment by akavel** [comment]
maybe https://github.com/kkawakam/rustyline ? I don't know how well it works, only that it's the first seemingly pure-Rust Google result for "rust readline windows" for me as of 2016.08

**Comment by murarth** [comment]
I'm working on a cross-platform readline alternative that will soon be released and that will solve this issue.

**Comment by akavel** [comment]
In the meantime, I've tried plugging in [rustyline](https://github.com/kkawakam/rustyline) as mentioned above. [My fork](https://github.com/akavel/rusti) [[diff](https://github.com/murarth/rusti/compare/master...akavel:master)] seems to build successfully with nightly-2016-08-01; but on `cargo run`, it shows no prompt, and then after pressing [Enter] I'm seeing an assertion failure:
```
C:\prog\rusti>cargo run -v
       Fresh encode_unicode v0.1.3
       Fresh lazy_static v0.2.1
       Fresh libc v0.2.15
       Fresh cfg-if v0.1.0
       Fresh regex-syntax v0.2.2
       Fresh unicode-width v0.1.3
       Fresh log v0.3.4
       Fresh getopts v0.2.14
       Fresh memchr v0.1.7
       Fresh winapi-build v0.1.1
       Fresh winapi v0.2.5
       Fresh aho-corasick v0.4.0
       Fresh regex v0.1.46
       Fresh env_logger v0.3.2
       Fresh kernel32-sys v0.2.1
       Fresh advapi32-sys v0.1.2
       Fresh rustyline v1.0.0
       Fresh rand v0.3.12
       Fresh tempfile v1.1.3
       Fresh rusti v0.0.1 (file:///C:/prog/rusti)
    Finished debug [unoptimized + debuginfo] target(s) in 0.17 secs
     Running `target\debug\rusti.exe`

Assertion failed!

Program: C:\prog\rusti\target\debug\rusti.exe
File: C:/bot/slave/nightly-dist-rustc-win-gnu-64/build/src/llvm/lib/ExecutionEngine/MCJIT/MCJIT.cpp, Line 198

Expression: M->getDataLayout() == getDataLayout() && "DataLayout Mismatch"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
error: Process didn't exit successfully: `target\debug\rusti.exe` (exit code: 3)

C:\prog\rusti>rustc --version
rustc 1.12.0-nightly (7333c4ac2 2016-07-31)
```

Do you have any idea what can this be about? (At first sight, it doesn't seem to be broken rustyline, as running: `C:\prog\rustyline> cargo run --example example` &mdash; seems to work ok for me.)

**Comment by akavel** [comment]
One more session in case you were interested, showing some slightly more interesting behavior before ultimately crashing too:
```
C:\prog\rusti>cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\rusti.exe`
print
<input>:12:20: 12:25 error: unresolved name `print`. Did you mean the macro `print!`? [E0425]
<input>:12 println!("{:?}", { print });
                              ^~~~~
<std macros>:2:27: 2:58 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<input>:12:1: 12:29 note: in this expansion of println! (defined in <std macros>)
error: aborting due to previous error
print
<input>:12:20: 12:25 error: unresolved name `print`. Did you mean the macro `print!`? [E0425]
<input>:12 println!("{:?}", { print });
                              ^~~~~
<std macros>:2:27: 2:58 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<input>:12:1: 12:29 note: in this expansion of println! (defined in <std macros>)
error: aborting due to previous error
println!("Hello");
Assertion failed!

Program: C:\prog\rusti\target\debug\rusti.exe
File: C:/bot/slave/nightly-dist-rustc-win-gnu-64/build/src/llvm/lib/ExecutionEngine/MCJIT/MCJIT.cpp, Line 198

Expression: M->getDataLayout() == getDataLayout() && "DataLayout Mismatch"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
error: Process didn't exit successfully: `target\debug\rusti.exe` (exit code: 3)
```

**Comment by murarth** [comment]
Closing this because the new input reader, [linefeed](https://github.com/murarth/linefeed), is both cross-platform and not readline.

@akavel: If you're still experiencing that error on the new HEAD of master, go ahead and file an issue for it.

**Comment by akavel** [comment]
unfortunately, still not good :(
