### ISSUE TITLE
Failed to build with rustc 1.4.0-nightly (1181679c8 2015-08-07)

### ISSUE THREAD

**Issue by xhevahir** [murarth/rusti#44]
src/rusti/repl.rs:436:18: 436:34 error: unresolved name `token::get_ident` [E0425]
src/rusti/repl.rs:436             if &*token::get_ident(ident) == self.fn_name {
                                       ^~~~~~~~~~~~~~~~
note: in expansion of if let expansion
src/rusti/repl.rs:435:9: 446:10 note: expansion site
src/rusti/repl.rs:436:18: 436:34 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
Could not compile `rusti`.

**Comment by murarth** [comment]
This was fixed a short while ago. Download the latest revision of `rusti` and it should build just fine.
