### ISSUE TITLE
does not run with latest nightly

### ISSUE THREAD

**Issue by durka** [murarth/rusti#49]
On nightly 2015-10-3:

    $ cargo run --release
    /Users/alex/Programming/rust/rusti/target/release/rusti: fork: retry: No child processes

The message repeats until the process is forcibly killed (^C, ^Z, etc, it takes a few).

OSX 10.9.5. Works fine with nightly-2015-09-19.

**Comment by honorabrutroll** [comment]
No issue here on nightly 2015-10-3 with Arch Linux (kernel 4.1.9-1-ck).

**Comment by murarth** [comment]
The error appears to be that the process is not being permitted to fork. `rusti` does fork once during the startup process, in order to run the command `rustc --print sysroot`. What kind of environment are you running this in? Does it have a particularly low value for `ulimit -u`?

**Comment by durka** [comment]
Huh... the error went away when I tried it again a few hours later. Maybe Spotlight was taking all the PIDs to reindex my hard drive, or something.
