### ISSUE TITLE
Racer completion not working

### ISSUE THREAD

**Issue by kookerus** [murarth/rusti#54]
I just installed rusti and racer, and added both to my path. Both are functional, but I can't get any completions in rusti. Did I install something wrong, or is this a bug?

**Comment by jonas-schievink** [comment]
Can you run with `RUST_LOG=rusti=debug` (I hope that's right) and post the output after trying to complete a path?

**Comment by kookerus** [comment]
I'm sorry, am I supposed to run that in the terminal before starting rusti? If that's the case, I'm not seeing any kind of log.

**Comment by jonas-schievink** [comment]
It's an environment variable that controls logging (the env_logger crate). Try running `RUST_LOG="rusti=debug" rusti`

**Comment by kookerus** [comment]
Pressing tab after typing "printl" gives:
<code>DEBUG:rusti::readline: completion fn on "printl", printl - 0 (6)
DEBUG:rusti::completion: completion input: text="printl" end=6</code>

**Comment by murarth** [comment]
@kookerus: It seems you're trying to get rusti to complete the name for the standard macro `println`. Using the version of `racer` I have currently installed, it appears that macros are simply not a candidate for completion. When I run `racer complete printl`, it produces no output. Compare to `racer complete std` which shows that `std` is a matching name.

**Comment by kookerus** [comment]
Okay, I see. Thanks for letting me know, sorry about taking up your time.
