### ISSUE TITLE
Cant run built executable

### ISSUE THREAD

**Issue by nicrgren** [murarth/rusti#60]
I can run rusti fine using cargo run, but whenever I build it using cargo build, both with and without --release and attempt to run rusti from the target/{debug|release} dir I get the following error:
`
dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-8cf6ce90.dylib
  Referenced from: /Users/mitur/gits/rusti/target/debug/./rusti
  Reason: image not found
[1]    61341 trace trap  ./rusti
`

I am building using multirust with nightly currently on rustc 1.6.0-nightly (8864f2c83 2015-12-07)

On osx  10.11.1

I would happily provide any other information that could help. 

Thanks

**Comment by murarth** [comment]
@mitur: Are you using multirust? Some googling has turned up what appear to be similar issues when using multirust.

**Comment by mitur** [comment]
@murarth Yes I am. Ok, I will check it out. 
Thanks for your quick reply, sorry for bringing it up here.

**Comment by kindlychung** [comment]
Someone found a solution:

```
multirust run nightly bash && rusti
```

See here: https://gist.github.com/paulp/dc018b84aeb9f7533322

**Comment by agaviria** [comment]
@murarth @kindlychung  Any suggestions for `rustup` users?  There seems to be a shared lib mismatch for the following:

```
        /usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Env: `OSX 10.11.6 - rustup nightly 2016-08-01`

**Comment by wuranbo** [comment]
@agaviria  same as you. OSX and rustup nightly 2016-08-01. Any help? Thank you.

**Comment by wuranbo** [comment]
@agaviria  I got 

    rustup run nightly-2016-08-01 ~/.cargo/bin/rusti 

work
