### ISSUE TITLE
Compilation failure in Ubuntu 14.04

### ISSUE THREAD

**Issue by JoePython1** [murarth/rusti#66]
$ rustc --version
rustc 1.5.0 (3d7cd77e4 2015-12-04)

$ cargo build
 Downloading tempfile v1.1.3
 Downloading getopts v0.2.14
 Downloading rand v0.3.12
   Compiling getopts v0.2.14
   Compiling winapi-build v0.1.1
   Compiling regex-syntax v0.2.2
   Compiling winapi v0.2.5
   Compiling libc v0.2.4
   Compiling kernel32-sys v0.2.1
   Compiling advapi32-sys v0.1.2
   Compiling memchr v0.1.7
   Compiling log v0.3.4
   Compiling aho-corasick v0.4.0
   Compiling rand v0.3.12
   Compiling regex v0.1.46
   Compiling tempfile v1.1.3
   Compiling env_logger v0.3.2
   Compiling rusti v0.0.1 (file:///home/joepython/Downloads/rusti)
src/rusti/lib.rs:12:1: 12:38 error: #[feature] may not be used on the stable release channel
src/rusti/lib.rs:12 #![feature(rustc_private, set_stdio)]
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rusti`.

To learn more, run the command again with --verbose.

**Comment by murarth** [comment]
As noted in the [Building](https://github.com/murarth/rusti/#building) section of the README, rusti cannot be built using the stable release of the Rust compiler. The nightly release is required to access unstable features, upon which rusti depends. You can use [multirust](https://github.com/brson/multirust) to enable the use of the nightly compiler only when building rusti.
