### ISSUE TITLE
Couldn't run rusti compiled with multirust : error while loading shared libraries

### ISSUE THREAD

**Issue by gowthamsadasivam** [murarth/rusti#69]
I was following the guidelines,

> Alternatively the nightly release can be used in the rusti directory tree using multirust and issuing the following command from rusti folder
> 
> multirust override nightly
> 
> Build with Cargo:
> 
> cargo build
> 
> Run rusti:
> 
> cargo run
 
And I got rusti running now. so I wanted to copy it to my /usr/local/bin directory to have it run out of the build directory as specified as,

> Cargo does not currently support an install subcommand, so if you would like to run rusti outside the build directory, you must manually copy target/rusti into a directory in your PATH environment variable.

But rusti didn't execute independently. Instead it drops an error: 
**error while loading shared libraries: librustc_driver-fd663c41.so: cannot open shared object file: No such file or directory** 

Screen:
![rusti](https://cloud.githubusercontent.com/assets/5887533/13353603/79d9e8bc-dcbb-11e5-934a-54580bd952c9.jpg)

**Comment by murarth** [comment]
`multirust` sets some environment variables when running `rustc` or `cargo`. If you run rusti as `multirust run nightly rusti`, it should set these variables. It may be most convenient to create an alias for this in your `~/.bashrc`.

**Comment by gowthamsadasivam** [comment]
Thanks for the quick response. Yes, running it by `multirust run nightly rusti` works great :+1:. It would be great to have this step in the README.ME file, will be really helpful for the first timers like me.
