### ISSUE TITLE
The license must be GPL

### ISSUE THREAD

**Issue by nodakai** [murarth/rusti#8]
GNU `libreadline` is released under GPL rather than LGPL.  That requires you to release your software which links to it under GPL when you distribute it.

- https://en.wikipedia.org/wiki/GNU_Readline#Choice_of_the_GPL_as_GNU_Readline.27s_license

I retract this statement: ~~Also, my understanding is GPL is compatible with neither of MIT nor Apache 2 License.~~

- https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing

See the former article for possible alternatives of `libreadline`.

**Comment by mitsuhiko** [comment]
There is no reason for the package to be GPL.  The final product will automatically degrade to GPL but the original source here should be BSD.  Also there are GPL interface compatible versions of libreadline which are not GPL licensed and APIs are not copyrightable.  So no reason for this to be GPL.

**Comment by murarth** [comment]
Seems reasonable to me. Thanks to both of you for the input. Closing this for now.
