### ISSUE TITLE
Discrepancy between help output and performed actions

### ISSUE THREAD

**Issue by JIghtuse** [murarth/rusti#80]
If you run rusti with `--help` option, it will tell you about:

1. Two options with arguments, which it executes and exits.

        -c COMMAND          Execute a rusti command and exit
        -e PROGRAM          Execute a one-line program and exit

2. Interactive mode option, which executes file and starts REPL.

        -i, --interactive   Run rusti interactively even with a file

Now, if you use `-i` with `-c` or `-e`, rusti will not exit, but starts REPL too.

So, the problem is one of:

- misleading help for `-c` and `-e` (should omit `exit` or tell about `-i`)
- incomplete help for `-i` (should also tell about `-c` and `-e`)
- wrong actions when `-i` used simultaneously with `-c` or `-e` (we should actually exit after executing arguments)

It should be pretty trivial to solve this issue after we choose correct action.

**Comment by murarth** [comment]
Yes, I agree that there is an absence of information in the help text for what `-i -e '...'` should do. I don't see any reason that `-i` shouldn't function when either `-c` or `-e` is present, so I'll go ahead and update the help text for `-i` to include this.

**Comment by JIghtuse** [comment]
@murarth thanks!
As a side note, can you look at https://github.com/JIghtuse/rusti/commit/993739b62c3949c7dc786496f855fec574d1d74d ? I tried to add `:edit` command and it kinda works. It is almost useless for now, because rusti can't "reload" source file. Do you think it would be useful?

**Comment by murarth** [comment]
Without the ability to reload files, I don't see the motivation of having an edit command. But it will be something to revisit when more code manipulation features are sorted out.
