### ISSUE TITLE
Unresolved import errors (Ubuntu 14.04, rustc 1.11.0 nightly, rusti 815b0ee)

### ISSUE THREAD

**Issue by SRGOM** [murarth/rusti#81]
I'm getting the following errors when compiling on Ubuntu 14.04 with rustc version rustc 1.11.0-nightly (bb4a79b08 2016-06-15), rusti version: 815b0ee506106fb05ff213312419a86eee422288

```
Compiling__ rusti v0.0.1 (file:///home/username/git/rusti)
src/rusti/exec.rs:40:5: 40:39 error: unresolved import `syntax::errors::registry::Registry`. Could not find `registry` in `syntax::errors` [E0432]
src/rusti/exec.rs:40 use syntax::errors::registry::Registry;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/rusti/exec.rs:40:5: 40:39 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:26:5: 26:40 error: unresolved import `syntax::errors::snippet::FormatMode`. There is no `FormatMode` in `syntax::errors::snippet` [E0432]
src/rusti/input.rs:26 use syntax::errors::snippet::FormatMode;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/rusti/input.rs:26:5: 26:40 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/repl.rs:453:22: 453:36 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
src/rusti/repl.rs:453 impl<'a, 'gcx, 'tcx> visit::Visitor for ExprType<'a, 'gcx, 'tcx> {
                                           ^~~~~~~~~~~~~~
src/rusti/repl.rs:453:22: 453:36 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `rusti`.

To learn more, run the command again with --verbose.

```

I have done a `sudo apt-get install libreadline-dev libedit-dev` before downloading the repo and doing a `cargo build`

**Comment by murarth** [comment]
Your nightly build is a bit outdated. There are frequent changes to rusti to keep up with nightly. (You can look for "Fix for nightly" commits in the commit log). So, you can either update to the current nightly build (be sure to pull from rusti again because I just merged a fix) or search for a nightly fix commit whose date precedes your current nightly.

**Comment by SRGOM** [comment]
I'm getting another set of errors fun the latest nightly.

**Comment by murarth** [comment]
Have you pulled from rusti again? There was another breaking change on today's nightly. I merged a fix just about an hour ago.

**Comment by SRGOM** [comment]
rustc 1.12.0-nightly (4db1874f4 2016-07-15) and rusti   ff1ae06 (which is my earlier rusti + your fix) play along fine and I can see rusti. Thanks for your maintaining this so actively.
