### ISSUE TITLE
Link failure: cannot find -lncursesw [fixed] 

### ISSUE THREAD

**Issue by nathanaeljones** [murarth/rusti#92]
If `rusti` fails to compile with link error `note: /usr/bin/ld: cannot find -lncursesw`, you need the development version of libncursesw 

On Ubuntu 14.04, this can be installed via apt-get.

`sudo apt-get install libncursesw5-dev`

Logging this issue for others searching the error message.

**Comment by softwaremechanic** [comment]
+1

**Comment by dineshadepu** [comment]
+1
