### ISSUE TITLE
Fail to build by cargo and git

### ISSUE THREAD

**Issue by ShalokShalom** [murarth/rusti#95]
My error message: https://gist.github.com/ShalokShalom/35f099c78e856c2ad948d91d52f9c520

**Comment by murarth** [comment]
rusti must be built with nightly 2016-08-01. The [building section of the README](https://github.com/murarth/rusti#building) gives instructions on how best to accomplish this, using `rustup`.

**Comment by ShalokShalom** [comment]
Then remove maybe this information from the homepage: https://github.com/murarth/rusti#installation-using-cargo

**Comment by coder543** [comment]
quoting from that section:

> rustup run nightly-2016-08-01 \ cargo install --git https://github.com/murarth/rusti

"cargo" is basically bundled with every release of Rust. I think the instructions are pretty clear that you have to be using the correct version of Rust.

rusti has been unmaintained for quite awhile now, for various reasons. It would be nice if it were maintained, but there doesn't seem to be enough interest.

**Comment by murarth** [comment]
@ShalokShalom: Fair point. The first `cargo install` command is misleading as it follows the stated suggestion to use `rustup`, but then does not itself use `rustup`. I've removed it, putting the proper `cargo install` command at the top of the installation section.
