### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by alexreg** [murarth/rusti#96]
This looks like a great project, though unfortunately it's well out-of-date, and could do with updates for the latest Rust (stable and nightly). Any chance of this happening?

**Comment by murarth** [comment]
As described in issue #86, the rustc API that was used to compile code in memory is no longer available. rusti cannot be updated for a new version of Rust until a new API exists to fill this role.

(Closing as duplicate of #86.)

**Comment by softprops** [comment]
:/
